data:
  ptbxl_path: "./data/ptbxl"
  custom_dataset_path: "./data/custom"
  batch_size: 16
  num_workers: 4
  sample_rate: 100
  duration: 10.0
  lead_names: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

model:
  student_dim: 256
  teacher_dim: 768
  student_depth: 8
  teacher_depth: 12
  student_num_heads: 8
  teacher_num_heads: 12
  mlp_ratio: 4.0
  patch_size: 32
  overlap: 8
  num_patches: 128
  dropout: 0.1
  out_dim: 65536
  metadata_dim: 64

training:
  epochs: 50
  warmup_epochs: 5
  learning_rate: 5e-5
  weight_decay: 0.04
  momentum_teacher: 0.996
  center_momentum: 0.9
  teacher_temp: 0.04
  warmup_teacher_temp: 0.04
  freeze_teacher_backbone: False
  freeze_student_backbone: False
  output_dir: "./output/finetune"
  save_every: 5
  log_every: 10

phase: "finetune"
