"""add schema_type

Revision ID: 64c4877625e5
Revises: 7bd1b5ea4f00
Create Date: 2025-04-15 08:47:16.598230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64c4877625e5"
down_revision: Union[str, None] = "7bd1b5ea4f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("schema_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "schema_type")
    # ### end Alembic commands ###
