"""add_project_name_org_unique_constraint

Revision ID: 65ade074ef17
Revises: 786d23d94b30
Create Date: 2025-04-09 13:03:02.333968

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "65ade074ef17"
down_revision: Union[str, None] = "786d23d94b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_project_org_name", "projects", ["organization_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_project_org_name", "projects", type_="unique")
    # ### end Alembic commands ###
