"""batch pointer

Revision ID: 7bd1b5ea4f00
Revises: 65ade074ef17
Create Date: 2025-04-11 18:11:08.421692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bd1b5ea4f00"
down_revision: Union[str, None] = "65ade074ef17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("first_batch_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "first_batch_id")
    # ### end Alembic commands ###
