"""Add batch processing status

Revision ID: ee10431c4992
Revises: a99dbe5cdfda
Create Date: 2025-05-16 21:49:07.305371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee10431c4992'
down_revision: Union[str, None] = 'a99dbe5cdfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('processing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'processing_status')
    # ### end Alembic commands ###
